//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonoDet
    {
        public decimal nAbonoDetPK { get; set; }
        public decimal nAbonoPK { get; set; }
        public string cMetodoPago { get; set; }
        public decimal mMonto { get; set; }
        public Nullable<decimal> nBancoPK { get; set; }
        public string cDigitos { get; set; }
    }
}
